# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Sanxi_CtrlUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Sanxi_form(object):
    def setupUi(self, Sanxi_form):
        Sanxi_form.setObjectName("Sanxi_form")
        Sanxi_form.resize(869, 619)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        Sanxi_form.setFont(font)
        self.Commu_groupBox = QtWidgets.QGroupBox(Sanxi_form)
        self.Commu_groupBox.setGeometry(QtCore.QRect(20, 10, 160, 160))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.Commu_groupBox.setFont(font)
        self.Commu_groupBox.setObjectName("Commu_groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Commu_groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 87, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.horizontalLayoutWidget.setFont(font)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.COM_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.COM_label.setFont(font)
        self.COM_label.setObjectName("COM_label")
        self.horizontalLayout.addWidget(self.COM_label)
        self.port_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.port_spinBox.setFont(font)
        self.port_spinBox.setProperty("value", 4)
        self.port_spinBox.setObjectName("port_spinBox")
        self.horizontalLayout.addWidget(self.port_spinBox)
        self.gridLayoutWidget = QtWidgets.QWidget(self.Commu_groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 88, 83))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget.setFont(font)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.disconnct_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.disconnct_pushButton.setFont(font)
        self.disconnct_pushButton.setObjectName("disconnct_pushButton")
        self.gridLayout.addWidget(self.disconnct_pushButton, 2, 0, 1, 1)
        self.connect_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.connect_pushButton.setFont(font)
        self.connect_pushButton.setObjectName("connect_pushButton")
        self.gridLayout.addWidget(self.connect_pushButton, 0, 0, 1, 1)
        self.searchorigin_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.searchorigin_pushButton.setFont(font)
        self.searchorigin_pushButton.setObjectName("searchorigin_pushButton")
        self.gridLayout.addWidget(self.searchorigin_pushButton, 1, 0, 1, 1)
        self.motionpara_groupBox = QtWidgets.QGroupBox(Sanxi_form)
        self.motionpara_groupBox.setGeometry(QtCore.QRect(20, 190, 160, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.motionpara_groupBox.setFont(font)
        self.motionpara_groupBox.setFlat(False)
        self.motionpara_groupBox.setCheckable(False)
        self.motionpara_groupBox.setObjectName("motionpara_groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.motionpara_groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 30, 121, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_2.setFont(font)
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.ve_verticalSlider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.ve_verticalSlider.setFont(font)
        self.ve_verticalSlider.setMinimum(0)
        self.ve_verticalSlider.setMaximum(100)
        self.ve_verticalSlider.setPageStep(10)
        self.ve_verticalSlider.setProperty("value", 10)
        self.ve_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.ve_verticalSlider.setObjectName("ve_verticalSlider")
        self.gridLayout_2.addWidget(self.ve_verticalSlider, 0, 0, 1, 1)
        self.ac_verticalSlider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.ac_verticalSlider.setFont(font)
        self.ac_verticalSlider.setMaximum(100)
        self.ac_verticalSlider.setPageStep(10)
        self.ac_verticalSlider.setProperty("value", 90)
        self.ac_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.ac_verticalSlider.setObjectName("ac_verticalSlider")
        self.gridLayout_2.addWidget(self.ac_verticalSlider, 0, 1, 1, 1)
        self.VE_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.VE_label.setFont(font)
        self.VE_label.setAlignment(QtCore.Qt.AlignCenter)
        self.VE_label.setObjectName("VE_label")
        self.gridLayout_2.addWidget(self.VE_label, 1, 0, 1, 1)
        self.AC_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.AC_label.setFont(font)
        self.AC_label.setAlignment(QtCore.Qt.AlignCenter)
        self.AC_label.setObjectName("AC_label")
        self.gridLayout_2.addWidget(self.AC_label, 1, 1, 1, 1)
        self.de_verticalSlider = QtWidgets.QSlider(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.de_verticalSlider.setFont(font)
        self.de_verticalSlider.setMaximum(100)
        self.de_verticalSlider.setPageStep(10)
        self.de_verticalSlider.setProperty("value", 30)
        self.de_verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.de_verticalSlider.setObjectName("de_verticalSlider")
        self.gridLayout_2.addWidget(self.de_verticalSlider, 0, 2, 1, 1)
        self.DE_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.DE_label.setFont(font)
        self.DE_label.setAlignment(QtCore.Qt.AlignCenter)
        self.DE_label.setObjectName("DE_label")
        self.gridLayout_2.addWidget(self.DE_label, 1, 2, 1, 1)
        self.motionparaOK_pushButton = QtWidgets.QPushButton(self.motionpara_groupBox)
        self.motionparaOK_pushButton.setGeometry(QtCore.QRect(40, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.motionparaOK_pushButton.setFont(font)
        self.motionparaOK_pushButton.setObjectName("motionparaOK_pushButton")
        self.func_groupBox = QtWidgets.QGroupBox(Sanxi_form)
        self.func_groupBox.setGeometry(QtCore.QRect(210, 10, 311, 481))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.func_groupBox.setFont(font)
        self.func_groupBox.setObjectName("func_groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.func_groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 220, 291, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 271, 102))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sendcode_textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.sendcode_textEdit.setFont(font)
        self.sendcode_textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sendcode_textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.sendcode_textEdit.setObjectName("sendcode_textEdit")
        self.verticalLayout.addWidget(self.sendcode_textEdit)
        self.sendcode_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.sendcode_pushButton.setFont(font)
        self.sendcode_pushButton.setObjectName("sendcode_pushButton")
        self.verticalLayout.addWidget(self.sendcode_pushButton)
        self.groupBox_3 = QtWidgets.QGroupBox(self.func_groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 100, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_3)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(30, 20, 235, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_4.setFont(font)
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.xread_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.xread_lineEdit.setFont(font)
        self.xread_lineEdit.setObjectName("xread_lineEdit")
        self.gridLayout_4.addWidget(self.xread_lineEdit, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.bread_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.bread_lineEdit.setFont(font)
        self.bread_lineEdit.setObjectName("bread_lineEdit")
        self.gridLayout_4.addWidget(self.bread_lineEdit, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 1, 2, 1, 1)
        self.yread_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.yread_lineEdit.setFont(font)
        self.yread_lineEdit.setObjectName("yread_lineEdit")
        self.gridLayout_4.addWidget(self.yread_lineEdit, 1, 1, 1, 1)
        self.p2p_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.p2p_pushButton.setFont(font)
        self.p2p_pushButton.setObjectName("p2p_pushButton")
        self.gridLayout_4.addWidget(self.p2p_pushButton, 0, 4, 1, 1)
        self.aread_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.aread_lineEdit.setFont(font)
        self.aread_lineEdit.setObjectName("aread_lineEdit")
        self.gridLayout_4.addWidget(self.aread_lineEdit, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 2, 0, 1, 1)
        self.zread_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.zread_lineEdit.setFont(font)
        self.zread_lineEdit.setObjectName("zread_lineEdit")
        self.gridLayout_4.addWidget(self.zread_lineEdit, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 2, 1, 1)
        self.cread_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.cread_lineEdit.setFont(font)
        self.cread_lineEdit.setObjectName("cread_lineEdit")
        self.gridLayout_4.addWidget(self.cread_lineEdit, 2, 3, 1, 1)
        self.goline_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.goline_pushButton.setFont(font)
        self.goline_pushButton.setObjectName("goline_pushButton")
        self.gridLayout_4.addWidget(self.goline_pushButton, 2, 4, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.func_groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 360, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(30, 20, 166, 81))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_5.setFont(font)
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 3, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_5.addWidget(self.label_10, 0, 3, 1, 1)
        self.j2read_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j2read_lineEdit.setFont(font)
        self.j2read_lineEdit.setObjectName("j2read_lineEdit")
        self.gridLayout_5.addWidget(self.j2read_lineEdit, 1, 2, 1, 1)
        self.j6read_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j6read_lineEdit.setFont(font)
        self.j6read_lineEdit.setObjectName("j6read_lineEdit")
        self.gridLayout_5.addWidget(self.j6read_lineEdit, 2, 4, 1, 1)
        self.j4read_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j4read_lineEdit.setFont(font)
        self.j4read_lineEdit.setObjectName("j4read_lineEdit")
        self.gridLayout_5.addWidget(self.j4read_lineEdit, 0, 4, 1, 1)
        self.j3read_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j3read_lineEdit.setFont(font)
        self.j3read_lineEdit.setObjectName("j3read_lineEdit")
        self.gridLayout_5.addWidget(self.j3read_lineEdit, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 1, 1, 1, 1)
        self.j5read_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j5read_lineEdit.setFont(font)
        self.j5read_lineEdit.setObjectName("j5read_lineEdit")
        self.gridLayout_5.addWidget(self.j5read_lineEdit, 1, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 1, 1, 1)
        self.j1read_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j1read_lineEdit.setFont(font)
        self.j1read_lineEdit.setObjectName("j1read_lineEdit")
        self.gridLayout_5.addWidget(self.j1read_lineEdit, 0, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_5.addWidget(self.label_9, 2, 1, 1, 1)
        self.goangle_pushButton = QtWidgets.QPushButton(self.groupBox_4)
        self.goangle_pushButton.setGeometry(QtCore.QRect(200, 40, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.goangle_pushButton.setFont(font)
        self.goangle_pushButton.setObjectName("goangle_pushButton")
        self.groupBox_5 = QtWidgets.QGroupBox(self.func_groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 291, 80))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(40, 20, 214, 54))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_6.setFont(font)
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.coorfile_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.coorfile_pushButton.setFont(font)
        self.coorfile_pushButton.setObjectName("coorfile_pushButton")
        self.gridLayout_6.addWidget(self.coorfile_pushButton, 0, 1, 1, 1)
        self.anglefile_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.anglefile_pushButton.setFont(font)
        self.anglefile_pushButton.setObjectName("anglefile_pushButton")
        self.gridLayout_6.addWidget(self.anglefile_pushButton, 0, 0, 1, 1)
        self.originalfile_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.originalfile_pushButton.setFont(font)
        self.originalfile_pushButton.setObjectName("originalfile_pushButton")
        self.gridLayout_6.addWidget(self.originalfile_pushButton, 1, 0, 1, 2)
        self.commi_groupBox = QtWidgets.QGroupBox(Sanxi_form)
        self.commi_groupBox.setGeometry(QtCore.QRect(550, 10, 301, 221))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.commi_groupBox.setFont(font)
        self.commi_groupBox.setObjectName("commi_groupBox")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.commi_groupBox)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(40, 20, 221, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_3.setFont(font)
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.J3_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.J3_label.setFont(font)
        self.J3_label.setObjectName("J3_label")
        self.gridLayout_3.addWidget(self.J3_label, 2, 0, 1, 1)
        self.J5_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.J5_label.setFont(font)
        self.J5_label.setObjectName("J5_label")
        self.gridLayout_3.addWidget(self.J5_label, 4, 0, 1, 1)
        self.J4_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.J4_label.setFont(font)
        self.J4_label.setObjectName("J4_label")
        self.gridLayout_3.addWidget(self.J4_label, 3, 0, 1, 1)
        self.J2_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.J2_label.setFont(font)
        self.J2_label.setObjectName("J2_label")
        self.gridLayout_3.addWidget(self.J2_label, 1, 0, 1, 1)
        self.J1_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.J1_label.setFont(font)
        self.J1_label.setObjectName("J1_label")
        self.gridLayout_3.addWidget(self.J1_label, 0, 0, 1, 1)
        self.j1ccw_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j1ccw_pushButton.setFont(font)
        self.j1ccw_pushButton.setObjectName("j1ccw_pushButton")
        self.gridLayout_3.addWidget(self.j1ccw_pushButton, 0, 2, 1, 1)
        self.j1cw_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j1cw_pushButton.setFont(font)
        self.j1cw_pushButton.setCheckable(False)
        self.j1cw_pushButton.setChecked(False)
        self.j1cw_pushButton.setAutoRepeat(False)
        self.j1cw_pushButton.setFlat(False)
        self.j1cw_pushButton.setObjectName("j1cw_pushButton")
        self.gridLayout_3.addWidget(self.j1cw_pushButton, 0, 1, 1, 1)
        self.J6_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.J6_label.setFont(font)
        self.J6_label.setObjectName("J6_label")
        self.gridLayout_3.addWidget(self.J6_label, 5, 0, 1, 1)
        self.j2up_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j2up_pushButton.setFont(font)
        self.j2up_pushButton.setObjectName("j2up_pushButton")
        self.gridLayout_3.addWidget(self.j2up_pushButton, 1, 1, 1, 1)
        self.j2down_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j2down_pushButton.setFont(font)
        self.j2down_pushButton.setObjectName("j2down_pushButton")
        self.gridLayout_3.addWidget(self.j2down_pushButton, 1, 2, 1, 1)
        self.j3up_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j3up_pushButton.setFont(font)
        self.j3up_pushButton.setObjectName("j3up_pushButton")
        self.gridLayout_3.addWidget(self.j3up_pushButton, 2, 1, 1, 1)
        self.j3down_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j3down_pushButton.setFont(font)
        self.j3down_pushButton.setObjectName("j3down_pushButton")
        self.gridLayout_3.addWidget(self.j3down_pushButton, 2, 2, 1, 1)
        self.j4cw_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j4cw_pushButton.setFont(font)
        self.j4cw_pushButton.setObjectName("j4cw_pushButton")
        self.gridLayout_3.addWidget(self.j4cw_pushButton, 3, 1, 1, 1)
        self.j4ccw_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j4ccw_pushButton.setFont(font)
        self.j4ccw_pushButton.setObjectName("j4ccw_pushButton")
        self.gridLayout_3.addWidget(self.j4ccw_pushButton, 3, 2, 1, 1)
        self.j5up_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j5up_pushButton.setFont(font)
        self.j5up_pushButton.setObjectName("j5up_pushButton")
        self.gridLayout_3.addWidget(self.j5up_pushButton, 4, 1, 1, 1)
        self.j5down_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j5down_pushButton.setFont(font)
        self.j5down_pushButton.setObjectName("j5down_pushButton")
        self.gridLayout_3.addWidget(self.j5down_pushButton, 4, 2, 1, 1)
        self.j6cw_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j6cw_pushButton.setFont(font)
        self.j6cw_pushButton.setObjectName("j6cw_pushButton")
        self.gridLayout_3.addWidget(self.j6cw_pushButton, 5, 1, 1, 1)
        self.j6ccw_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j6ccw_pushButton.setFont(font)
        self.j6ccw_pushButton.setObjectName("j6ccw_pushButton")
        self.gridLayout_3.addWidget(self.j6ccw_pushButton, 5, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(Sanxi_form)
        self.groupBox_6.setGeometry(QtCore.QRect(550, 240, 301, 371))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 281, 121))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.returncode_textBrowser = QtWidgets.QTextBrowser(self.groupBox)
        self.returncode_textBrowser.setGeometry(QtCore.QRect(10, 20, 261, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.returncode_textBrowser.setFont(font)
        self.returncode_textBrowser.setMouseTracking(False)
        self.returncode_textBrowser.setAutoFillBackground(False)
        self.returncode_textBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.returncode_textBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.returncode_textBrowser.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.returncode_textBrowser.setObjectName("returncode_textBrowser")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 150, 181, 101))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_7)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 161, 77))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_9.setFont(font)
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_9.addWidget(self.label_18, 2, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_9.addWidget(self.label_15, 0, 0, 1, 1)
        self.xshow_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.xshow_lineEdit.setFont(font)
        self.xshow_lineEdit.setText("")
        self.xshow_lineEdit.setReadOnly(True)
        self.xshow_lineEdit.setObjectName("xshow_lineEdit")
        self.gridLayout_9.addWidget(self.xshow_lineEdit, 0, 1, 1, 1)
        self.ashow_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.ashow_lineEdit.setFont(font)
        self.ashow_lineEdit.setReadOnly(True)
        self.ashow_lineEdit.setObjectName("ashow_lineEdit")
        self.gridLayout_9.addWidget(self.ashow_lineEdit, 0, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_9.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_9.addWidget(self.label_16, 1, 2, 1, 1)
        self.zshow_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.zshow_lineEdit.setFont(font)
        self.zshow_lineEdit.setText("")
        self.zshow_lineEdit.setReadOnly(True)
        self.zshow_lineEdit.setObjectName("zshow_lineEdit")
        self.gridLayout_9.addWidget(self.zshow_lineEdit, 2, 1, 1, 1)
        self.cshow_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.cshow_lineEdit.setFont(font)
        self.cshow_lineEdit.setReadOnly(True)
        self.cshow_lineEdit.setObjectName("cshow_lineEdit")
        self.gridLayout_9.addWidget(self.cshow_lineEdit, 2, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 0, 2, 1, 1)
        self.yshow_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.yshow_lineEdit.setFont(font)
        self.yshow_lineEdit.setReadOnly(True)
        self.yshow_lineEdit.setObjectName("yshow_lineEdit")
        self.gridLayout_9.addWidget(self.yshow_lineEdit, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_9.addWidget(self.label_17, 2, 0, 1, 1)
        self.bshow_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.bshow_lineEdit.setFont(font)
        self.bshow_lineEdit.setReadOnly(True)
        self.bshow_lineEdit.setObjectName("bshow_lineEdit")
        self.gridLayout_9.addWidget(self.bshow_lineEdit, 1, 3, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 260, 181, 101))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_8)
        self.gridLayoutWidget_10.setGeometry(QtCore.QRect(10, 20, 161, 77))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.gridLayoutWidget_10.setFont(font)
        self.gridLayoutWidget_10.setObjectName("gridLayoutWidget_10")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_10)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_10.addWidget(self.label_22, 1, 2, 1, 1)
        self.j5show_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j5show_lineEdit.setFont(font)
        self.j5show_lineEdit.setReadOnly(True)
        self.j5show_lineEdit.setObjectName("j5show_lineEdit")
        self.gridLayout_10.addWidget(self.j5show_lineEdit, 1, 3, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_10.addWidget(self.label_20, 1, 0, 1, 1)
        self.j6show_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j6show_lineEdit.setFont(font)
        self.j6show_lineEdit.setReadOnly(True)
        self.j6show_lineEdit.setObjectName("j6show_lineEdit")
        self.gridLayout_10.addWidget(self.j6show_lineEdit, 2, 3, 1, 1)
        self.j2show_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j2show_lineEdit.setFont(font)
        self.j2show_lineEdit.setReadOnly(True)
        self.j2show_lineEdit.setObjectName("j2show_lineEdit")
        self.gridLayout_10.addWidget(self.j2show_lineEdit, 1, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_10.addWidget(self.label_23, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 0, 0, 1, 1)
        self.j4show_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j4show_lineEdit.setFont(font)
        self.j4show_lineEdit.setReadOnly(True)
        self.j4show_lineEdit.setObjectName("j4show_lineEdit")
        self.gridLayout_10.addWidget(self.j4show_lineEdit, 0, 3, 1, 1)
        self.j3show_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j3show_lineEdit.setFont(font)
        self.j3show_lineEdit.setText("")
        self.j3show_lineEdit.setReadOnly(True)
        self.j3show_lineEdit.setObjectName("j3show_lineEdit")
        self.gridLayout_10.addWidget(self.j3show_lineEdit, 2, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 0, 2, 1, 1)
        self.j1show_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.j1show_lineEdit.setFont(font)
        self.j1show_lineEdit.setReadOnly(True)
        self.j1show_lineEdit.setObjectName("j1show_lineEdit")
        self.gridLayout_10.addWidget(self.j1show_lineEdit, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout_10.addWidget(self.label_24, 2, 2, 1, 1)
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_9.setGeometry(QtCore.QRect(200, 150, 91, 211))
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 77, 201))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rectmode_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rectmode_pushButton.setFont(font)
        self.rectmode_pushButton.setStatusTip("")
        self.rectmode_pushButton.setObjectName("rectmode_pushButton")
        self.verticalLayout_2.addWidget(self.rectmode_pushButton)
        self.anglemode_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.anglemode_pushButton.setFont(font)
        self.anglemode_pushButton.setObjectName("anglemode_pushButton")
        self.verticalLayout_2.addWidget(self.anglemode_pushButton)
        self.copycode_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.copycode_pushButton.setFont(font)
        self.copycode_pushButton.setObjectName("copycode_pushButton")
        self.verticalLayout_2.addWidget(self.copycode_pushButton)
        self.copyvalue_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.copyvalue_pushButton.setFont(font)
        self.copyvalue_pushButton.setObjectName("copyvalue_pushButton")
        self.verticalLayout_2.addWidget(self.copyvalue_pushButton)
        self.groupBox_10 = QtWidgets.QGroupBox(Sanxi_form)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 500, 501, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.backtoorigin_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.backtoorigin_pushButton.setGeometry(QtCore.QRect(20, 30, 100, 62))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.backtoorigin_pushButton.setFont(font)
        self.backtoorigin_pushButton.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.backtoorigin_pushButton.setObjectName("backtoorigin_pushButton")
        self.stop_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.stop_pushButton.setGeometry(QtCore.QRect(260, 30, 100, 62))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.stop_pushButton.setFont(font)
        self.stop_pushButton.setStyleSheet("background-color: rgb(85, 170, 127);")
        self.stop_pushButton.setObjectName("stop_pushButton")
        self.quit_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.quit_pushButton.setGeometry(QtCore.QRect(380, 30, 100, 62))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(True)
        self.quit_pushButton.setFont(font)
        self.quit_pushButton.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.quit_pushButton.setObjectName("quit_pushButton")
        self.call_v51exe_pushButton = QtWidgets.QPushButton(self.groupBox_10)
        self.call_v51exe_pushButton.setGeometry(QtCore.QRect(140, 30, 100, 62))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.call_v51exe_pushButton.setFont(font)
        self.call_v51exe_pushButton.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.call_v51exe_pushButton.setObjectName("call_v51exe_pushButton")

        self.retranslateUi(Sanxi_form)
        QtCore.QMetaObject.connectSlotsByName(Sanxi_form)
        Sanxi_form.setTabOrder(self.port_spinBox, self.connect_pushButton)
        Sanxi_form.setTabOrder(self.connect_pushButton, self.searchorigin_pushButton)
        Sanxi_form.setTabOrder(self.searchorigin_pushButton, self.disconnct_pushButton)
        Sanxi_form.setTabOrder(self.disconnct_pushButton, self.ve_verticalSlider)
        Sanxi_form.setTabOrder(self.ve_verticalSlider, self.ac_verticalSlider)
        Sanxi_form.setTabOrder(self.ac_verticalSlider, self.de_verticalSlider)
        Sanxi_form.setTabOrder(self.de_verticalSlider, self.motionparaOK_pushButton)
        Sanxi_form.setTabOrder(self.motionparaOK_pushButton, self.anglefile_pushButton)
        Sanxi_form.setTabOrder(self.anglefile_pushButton, self.coorfile_pushButton)
        Sanxi_form.setTabOrder(self.coorfile_pushButton, self.originalfile_pushButton)
        Sanxi_form.setTabOrder(self.originalfile_pushButton, self.xread_lineEdit)
        Sanxi_form.setTabOrder(self.xread_lineEdit, self.yread_lineEdit)
        Sanxi_form.setTabOrder(self.yread_lineEdit, self.zread_lineEdit)
        Sanxi_form.setTabOrder(self.zread_lineEdit, self.aread_lineEdit)
        Sanxi_form.setTabOrder(self.aread_lineEdit, self.bread_lineEdit)
        Sanxi_form.setTabOrder(self.bread_lineEdit, self.cread_lineEdit)
        Sanxi_form.setTabOrder(self.cread_lineEdit, self.p2p_pushButton)
        Sanxi_form.setTabOrder(self.p2p_pushButton, self.goline_pushButton)
        Sanxi_form.setTabOrder(self.goline_pushButton, self.sendcode_textEdit)
        Sanxi_form.setTabOrder(self.sendcode_textEdit, self.sendcode_pushButton)
        Sanxi_form.setTabOrder(self.sendcode_pushButton, self.j1read_lineEdit)
        Sanxi_form.setTabOrder(self.j1read_lineEdit, self.j2read_lineEdit)
        Sanxi_form.setTabOrder(self.j2read_lineEdit, self.j3read_lineEdit)
        Sanxi_form.setTabOrder(self.j3read_lineEdit, self.j4read_lineEdit)
        Sanxi_form.setTabOrder(self.j4read_lineEdit, self.j5read_lineEdit)
        Sanxi_form.setTabOrder(self.j5read_lineEdit, self.j6read_lineEdit)
        Sanxi_form.setTabOrder(self.j6read_lineEdit, self.goangle_pushButton)
        Sanxi_form.setTabOrder(self.goangle_pushButton, self.backtoorigin_pushButton)
        Sanxi_form.setTabOrder(self.backtoorigin_pushButton, self.call_v51exe_pushButton)
        Sanxi_form.setTabOrder(self.call_v51exe_pushButton, self.stop_pushButton)
        Sanxi_form.setTabOrder(self.stop_pushButton, self.quit_pushButton)
        Sanxi_form.setTabOrder(self.quit_pushButton, self.j1cw_pushButton)
        Sanxi_form.setTabOrder(self.j1cw_pushButton, self.j1ccw_pushButton)
        Sanxi_form.setTabOrder(self.j1ccw_pushButton, self.j2up_pushButton)
        Sanxi_form.setTabOrder(self.j2up_pushButton, self.j2down_pushButton)
        Sanxi_form.setTabOrder(self.j2down_pushButton, self.j3up_pushButton)
        Sanxi_form.setTabOrder(self.j3up_pushButton, self.j3down_pushButton)
        Sanxi_form.setTabOrder(self.j3down_pushButton, self.j4cw_pushButton)
        Sanxi_form.setTabOrder(self.j4cw_pushButton, self.j4ccw_pushButton)
        Sanxi_form.setTabOrder(self.j4ccw_pushButton, self.j5up_pushButton)
        Sanxi_form.setTabOrder(self.j5up_pushButton, self.j5down_pushButton)
        Sanxi_form.setTabOrder(self.j5down_pushButton, self.j6cw_pushButton)
        Sanxi_form.setTabOrder(self.j6cw_pushButton, self.j6ccw_pushButton)
        Sanxi_form.setTabOrder(self.j6ccw_pushButton, self.returncode_textBrowser)
        Sanxi_form.setTabOrder(self.returncode_textBrowser, self.xshow_lineEdit)
        Sanxi_form.setTabOrder(self.xshow_lineEdit, self.yshow_lineEdit)
        Sanxi_form.setTabOrder(self.yshow_lineEdit, self.zshow_lineEdit)
        Sanxi_form.setTabOrder(self.zshow_lineEdit, self.ashow_lineEdit)
        Sanxi_form.setTabOrder(self.ashow_lineEdit, self.bshow_lineEdit)
        Sanxi_form.setTabOrder(self.bshow_lineEdit, self.cshow_lineEdit)
        Sanxi_form.setTabOrder(self.cshow_lineEdit, self.j1show_lineEdit)
        Sanxi_form.setTabOrder(self.j1show_lineEdit, self.j2show_lineEdit)
        Sanxi_form.setTabOrder(self.j2show_lineEdit, self.j3show_lineEdit)
        Sanxi_form.setTabOrder(self.j3show_lineEdit, self.j4show_lineEdit)
        Sanxi_form.setTabOrder(self.j4show_lineEdit, self.j5show_lineEdit)
        Sanxi_form.setTabOrder(self.j5show_lineEdit, self.j6show_lineEdit)
        Sanxi_form.setTabOrder(self.j6show_lineEdit, self.rectmode_pushButton)
        Sanxi_form.setTabOrder(self.rectmode_pushButton, self.anglemode_pushButton)
        Sanxi_form.setTabOrder(self.anglemode_pushButton, self.copycode_pushButton)
        Sanxi_form.setTabOrder(self.copycode_pushButton, self.copyvalue_pushButton)

    def retranslateUi(self, Sanxi_form):
        _translate = QtCore.QCoreApplication.translate
        Sanxi_form.setWindowTitle(_translate("Sanxi_form", "Form"))
        self.Commu_groupBox.setTitle(_translate("Sanxi_form", "Communication/Start up"))
        self.COM_label.setText(_translate("Sanxi_form", "COM："))
        self.disconnct_pushButton.setText(_translate("Sanxi_form", "Disconnect"))
        self.connect_pushButton.setText(_translate("Sanxi_form", "Connect"))
        self.searchorigin_pushButton.setWhatsThis(_translate("Sanxi_form", "start the reset program by photoelectric switch"))
        self.searchorigin_pushButton.setText(_translate("Sanxi_form", "Search Origin"))
        self.motionpara_groupBox.setTitle(_translate("Sanxi_form", "Motion Parameters"))
        self.VE_label.setWhatsThis(_translate("Sanxi_form", "velocity"))
        self.VE_label.setText(_translate("Sanxi_form", "VE"))
        self.AC_label.setWhatsThis(_translate("Sanxi_form", "acceleration"))
        self.AC_label.setText(_translate("Sanxi_form", "AC"))
        self.DE_label.setWhatsThis(_translate("Sanxi_form", "deceleration"))
        self.DE_label.setText(_translate("Sanxi_form", "DE"))
        self.motionparaOK_pushButton.setText(_translate("Sanxi_form", "Apply"))
        self.func_groupBox.setTitle(_translate("Sanxi_form", "Functions"))
        self.groupBox_2.setTitle(_translate("Sanxi_form", "Send Code"))
        self.sendcode_textEdit.setHtml(_translate("Sanxi_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.sendcode_pushButton.setText(_translate("Sanxi_form", "Send Code (Mode 14)"))
        self.groupBox_3.setTitle(_translate("Sanxi_form", "Run Point"))
        self.label_3.setText(_translate("Sanxi_form", "A"))
        self.label_5.setText(_translate("Sanxi_form", "Y"))
        self.xread_lineEdit.setText(_translate("Sanxi_form", "300"))
        self.label.setText(_translate("Sanxi_form", "X"))
        self.bread_lineEdit.setText(_translate("Sanxi_form", "180"))
        self.label_4.setText(_translate("Sanxi_form", "B"))
        self.yread_lineEdit.setText(_translate("Sanxi_form", "0"))
        self.p2p_pushButton.setText(_translate("Sanxi_form", "P to P"))
        self.aread_lineEdit.setText(_translate("Sanxi_form", "0"))
        self.label_2.setText(_translate("Sanxi_form", "Z"))
        self.zread_lineEdit.setText(_translate("Sanxi_form", "500"))
        self.label_6.setText(_translate("Sanxi_form", "C"))
        self.cread_lineEdit.setText(_translate("Sanxi_form", "0"))
        self.goline_pushButton.setText(_translate("Sanxi_form", "Go Line"))
        self.groupBox_4.setTitle(_translate("Sanxi_form", "Run angle"))
        self.label_11.setText(_translate("Sanxi_form", "J5"))
        self.label_12.setText(_translate("Sanxi_form", "J6"))
        self.label_10.setText(_translate("Sanxi_form", "J4"))
        self.j2read_lineEdit.setText(_translate("Sanxi_form", "0"))
        self.j6read_lineEdit.setText(_translate("Sanxi_form", "0"))
        self.j4read_lineEdit.setText(_translate("Sanxi_form", "0"))
        self.j3read_lineEdit.setText(_translate("Sanxi_form", "-90"))
        self.label_8.setText(_translate("Sanxi_form", "J2"))
        self.j5read_lineEdit.setText(_translate("Sanxi_form", "-90"))
        self.label_7.setText(_translate("Sanxi_form", "J1"))
        self.j1read_lineEdit.setText(_translate("Sanxi_form", "0"))
        self.label_9.setText(_translate("Sanxi_form", "J3"))
        self.goangle_pushButton.setText(_translate("Sanxi_form", "Go Angle"))
        self.groupBox_5.setTitle(_translate("Sanxi_form", "Output File Control"))
        self.coorfile_pushButton.setText(_translate("Sanxi_form", "Output Coordinates"))
        self.anglefile_pushButton.setText(_translate("Sanxi_form", "Output Angles"))
        self.originalfile_pushButton.setText(_translate("Sanxi_form", "Output Original Data"))
        self.commi_groupBox.setTitle(_translate("Sanxi_form", "Commissioning"))
        self.J3_label.setText(_translate("Sanxi_form", "J3："))
        self.J5_label.setText(_translate("Sanxi_form", "J5："))
        self.J4_label.setText(_translate("Sanxi_form", "J4："))
        self.J2_label.setText(_translate("Sanxi_form", "J2："))
        self.J1_label.setText(_translate("Sanxi_form", "J1："))
        self.j1ccw_pushButton.setText(_translate("Sanxi_form", "Counterclockwise"))
        self.j1cw_pushButton.setText(_translate("Sanxi_form", "Clockwise"))
        self.J6_label.setText(_translate("Sanxi_form", "J6："))
        self.j2up_pushButton.setText(_translate("Sanxi_form", "Up"))
        self.j2down_pushButton.setText(_translate("Sanxi_form", "Down"))
        self.j3up_pushButton.setText(_translate("Sanxi_form", "Up"))
        self.j3down_pushButton.setText(_translate("Sanxi_form", "Down"))
        self.j4cw_pushButton.setText(_translate("Sanxi_form", "Clockwise"))
        self.j4ccw_pushButton.setText(_translate("Sanxi_form", "Counterclockwise"))
        self.j5up_pushButton.setText(_translate("Sanxi_form", "Up"))
        self.j5down_pushButton.setText(_translate("Sanxi_form", "Down"))
        self.j6cw_pushButton.setText(_translate("Sanxi_form", "Clockwise"))
        self.j6ccw_pushButton.setText(_translate("Sanxi_form", "Counterclockwise"))
        self.groupBox_6.setTitle(_translate("Sanxi_form", "Display Board"))
        self.groupBox.setTitle(_translate("Sanxi_form", "Return Code"))
        self.groupBox_7.setTitle(_translate("Sanxi_form", "Rectangular"))
        self.label_18.setText(_translate("Sanxi_form", "C"))
        self.label_15.setText(_translate("Sanxi_form", "X"))
        self.label_14.setText(_translate("Sanxi_form", "Y"))
        self.label_16.setText(_translate("Sanxi_form", "B"))
        self.label_13.setText(_translate("Sanxi_form", "A"))
        self.label_17.setText(_translate("Sanxi_form", "Z"))
        self.groupBox_8.setTitle(_translate("Sanxi_form", "Joint Angles"))
        self.label_22.setText(_translate("Sanxi_form", "5"))
        self.label_20.setText(_translate("Sanxi_form", "2"))
        self.label_23.setText(_translate("Sanxi_form", "3"))
        self.label_21.setText(_translate("Sanxi_form", "1"))
        self.label_19.setText(_translate("Sanxi_form", "4"))
        self.label_24.setText(_translate("Sanxi_form", "6"))
        self.groupBox_9.setTitle(_translate("Sanxi_form", "Control"))
        self.rectmode_pushButton.setWhatsThis(_translate("Sanxi_form", "show coordinate values"))
        self.rectmode_pushButton.setText(_translate("Sanxi_form", "Rect.\n"
"Mode"))
        self.anglemode_pushButton.setWhatsThis(_translate("Sanxi_form", "show joint angle values"))
        self.anglemode_pushButton.setText(_translate("Sanxi_form", "Angle\n"
"Mode"))
        self.copycode_pushButton.setWhatsThis(_translate("Sanxi_form", "copy return code to log file"))
        self.copycode_pushButton.setText(_translate("Sanxi_form", "Copy\n"
"Code"))
        self.copyvalue_pushButton.setWhatsThis(_translate("Sanxi_form", "copy coordinates/angle values to log file"))
        self.copyvalue_pushButton.setText(_translate("Sanxi_form", "Copy\n"
"Value"))
        self.groupBox_10.setTitle(_translate("Sanxi_form", "Core Functions"))
        self.backtoorigin_pushButton.setText(_translate("Sanxi_form", "Back\n"
"To Origin"))
        self.stop_pushButton.setText(_translate("Sanxi_form", "STOP"))
        self.quit_pushButton.setWhatsThis(_translate("Sanxi_form", "back to origin then quit"))
        self.quit_pushButton.setText(_translate("Sanxi_form", "QUIT"))
        self.call_v51exe_pushButton.setText(_translate("Sanxi_form", "Call\n"
"V51.exe"))

